# general settings
name: hist_rain
model_type: ImageCleanModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_PairedImage
    dataroot_gt: /home/min/Documents/ntire25/raindrop/GT
    dataroot_lq: /home/min/Documents/ntire25/raindrop/Input
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8

    # ### -------------Progressive training--------------------------
    # mini_batch_sizes: [8,4,4,2,1,1]             # Batch size per gpu
    # iters: [46000,32000,24000,18000,18000,12000]
    # gt_size: 1000 # 1280  1600  # Max patch size for progressive training
    # gt_sizes: [256,320,400,512,800,1000] # [128,160,192,256,320,384]  # Patch sizes for progressive training.
    # ### ------------------------------------------------------------

    ### ------- Training on single fixed-patch size 128x128---------
    mini_batch_sizes: [4]
    iters: [300000]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
    gt_size: 480  # 850 is close the maximum for batch size(1).
    gt_sizes: [480]
    ### ------------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_PairedImage
    # dataroot_gt: /home/min/Documents/ntire25/data/validation/Input
    dataroot_gt: /home/min/Documents/ntire25/data/my_val/GT
    # dataroot_lq: /home/min/Documents/ntire25/data/validation/Input
    dataroot_lq: /home/min/Documents/ntire25/data/my_val/LL
    io_backend:
      type: disk

# network structures
network_g:
  type: UHDM

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  total_iter: 150000
  warmup_iter: -1 # no warm up
  use_grad_clip: true

  # Split 300k iterations into two cycles. 
  # 1st cycle: fixed 3e-4 LR for 92k iters. 
  # 2nd cycle: cosine annealing (3e-4 to 1e-6) for 208k iters.
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [46000, 104000]       
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001]   
  
  mixing_augs:
    mixup: true # false # true
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: Adam
    lr: !!float 2e-4
    # weight_decay: !!float 1e-4
    betas: [0.9, 0.999]
  
  # losses
  pixel_opt:
    type: multi_VGGPerceptualLoss # multi_VGGPerceptualLoss  CharbonnierLoss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  window_size: 4
  val_freq: !!float 5e6
  save_img: true
  rgb2bgr: true
  use_image: false
  max_minibatch: 1

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
